### ISSUE TITLE
Vintage Craft caused a server side crash so wicked that a crash report didn't generate.

### ISSUE THREAD

**Issue by kreezxil** [tyronx/vintagecraft#9]
```
[15:56:51] [Server thread/FATAL] [FML/]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:56) ~[adw.class:?]
        at net.minecraft.block.Block.func_180635_a(Block.java:505) ~[atr.class:?]
        at net.minecraft.block.Block.func_180653_a(Block.java:486) ~[atr.class:?]
        at at.tyron.vintagecraft.Block.BlockVC.func_180653_a(BlockVC.java:266) ~[BlockVC.class:?]
        at at.tyron.vintagecraft.Block.Organic.BlockLeavesVC.func_180653_a(BlockLeavesVC.java:162) ~[BlockLeavesVC.class:?]
        at net.minecraft.block.Block.func_176226_b(Block.java:472) ~[atr.class:?]
        at net.minecraft.block.Block.func_180657_a(Block.java:807) ~[atr.class:?]
        at at.tyron.vintagecraft.Block.BlockVC.func_180657_a(BlockVC.java:255) ~[BlockVC.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:319) ~[qx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:241) ~[qx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:537) ~[rj.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) ~[ml.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ml.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
        ... 5 more
```

**Comment by kreezxil** [comment]
and like the last error that I reported at #7 it happened in a heavily wooded area.

**Comment by kreezxil** [comment]
also there is a new bug report per your request at #7

**Comment by tyronx** [comment]
Ok thanks for taking the efforts of testing. Both crashes are from the same cause. It should be fixed now. Can't be 100% sure because the crash reports give me only vague information. If it crashes again  however it should now print out more details as to why it crashes.

I will release v0.7.80 that contains these changes today or tomorrow.
